plugins {
    id 'java'
    id("com.gradleup.shadow") version "9.3.0"
}

jar {
    manifest {
        attributes(
            'Main-Class': 'CodeGenerator'
        )
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('/SysML-v2-Pilot-Implementation/org.omg.sysml.interactive/target/org.omg.sysml.interactive-0.55.0-SNAPSHOT-all.jar')
    implementation files('/SysML-v2-Pilot-Implementation/org.omg.sysml.interactive/target/org.omg.sysml.interactive-0.55.0-SNAPSHOT-sources.jar')

    implementation 'org.freemarker:freemarker:2.3.34'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.14.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.14.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:5.14.2'
}

test {
    useJUnitPlatform()
}
